## Expired Futures
When searching for an expired asset, you will need to specify the date range based on the ExpiryDate property.

In [52]:
import lseg.data as ld
from lseg.data.content import search
import pandas as pd
import datetime as dt
import dateutil.relativedelta

# Default session - desktop
ld.open_session()

In [53]:
pd.set_option('display.max_colwidth', 140)
ld.__version__

'2.1.1'

#### Example - Expired Vodafone futures in the month of Nov 2024.

In [4]:
ld.discovery.search(
    view = search.Views.DERIVATIVE_QUOTES,
    filter = "TickerSymbol eq 'vod' and ExpiryDate lt 2024-12-01 and ExpiryDate ge 2024-11-01",
    select = "DTSubjectName, ExchangeName, RIC, RCSAssetCategoryLeaf, AssetState, ExpiryDate, UnderlyingQuoteRIC"
)

,DTSubjectName,ExchangeName,RIC,RCSAssetCategoryLeaf,AssetState,ExpiryDate,UnderlyingQuoteRIC
0,Johannesburg Stock Exchange Vodacom Group SSF Equity Future Nov 2024,Johannesburg Stock Exchange,VODQX4^2,Equity Future,DC,2024-11-21,[VODJ.J]
1,Johannesburg Stock Exchange Vodacom Group Limited Cash Settled SSF Equity Future Nov 2024,Johannesburg Stock Exchange,VODSX4^2,Equity Future,DC,2024-11-21,[VODJ.J]

#### Example - Expired Crude Oil Futures in the last year

In [41]:
# Build expiry date range expression
date_1_year_ago = dt.datetime.today() - dateutil.relativedelta.relativedelta(days=365)
date_range = f'ExpiryDate ge {date_1_year_ago.strftime("%Y-%m-%d")} and ExpiryDate lt {dt.datetime.today().strftime("%Y-%m-%d")}'
date_range

'ExpiryDate ge 2025-03-12 and ExpiryDate lt 2026-03-12'

In [48]:
ld.discovery.search(
    view=search.Views.COMMODITY_QUOTES,
    filter = f"SearchAllCategoryv2 eq 'Commodities' and \
               RCSUnderlyingProductLeaf in ('Brent Crude' 'WTI Crude') and \
               RCSAssetCategoryLeaf xeq 'Commodity Future' and {date_range}",
    order_by = "ExpiryDate desc",
    top = 30,
    select = "DTSubjectName, RIC, ExpiryDate, RCSUnderlyingProductLeaf",
)

,DTSubjectName,RIC,ExpiryDate,RCSUnderlyingProductLeaf
0,NYMEX Brent CFD: Dated Brent (Platts) vs. Brent Second Month (Platts) Daily Electronic Energy Future Mar 2026,A6W11H26,2026-03-11,Brent Crude
1,NYMEX Daily WTI Financial Electronic Energy Future Mar 2026,DCL11H26,2026-03-11,WTI Crude
2,NYMEX Dated Brent (Platts) Daily Electronic Energy Future Mar 2026,A7T11H26,2026-03-11,Brent Crude
3,NYMEX Dated Brent (Platts) vs. Brent Second Month (BFOE) (Platts) Daily CFD Electronic Energy Futures Mar 2026,A59G11H26,2026-03-11,Brent Crude
4,NYMEX Brent CFD: Dated Brent (Platts) vs. Brent Second Month (Platts) Daily Electronic Energy Future Mar 2026,A6W10H26,2026-03-10,Brent Crude
5,NYMEX Dated Brent (Platts) vs. Brent Second Month (BFOE) (Platts) Daily CFD Electronic Energy Futures Mar 2026,A59G10H26,2026-03-10,Brent Crude
6,NYMEX Dated Brent (Platts) Daily Electronic Energy Future Mar 2026,A7T10H26,2026-03-10,Brent Crude
7,NYMEX Daily WTI Financial Electronic Energy Future Mar 2026,DCL10H26,2026-03-10,WTI Crude
8,NYMEX Dated Brent (Platts) vs. Brent Second Month (BFOE) (Platts) Daily CFD Electronic Energy Futures Mar 2026,A59G9H26,2026-03-09,Brent Crude
9,NYMEX Dated Brent (Platts) Daily Electronic Energy Future Mar 2026,A7T9H26,2026-03-09,Brent Crude
10,NYMEX Daily WTI Financial Electronic Energy Future Mar 2026,DCL9H26,2026-03-09,WTI Crude
11,NYMEX Brent CFD: Dated Brent (Platts) vs. Brent Second Month (Platts) Daily Electronic Energy Future Mar 2026,A6W9H26,2026-03-09,Brent Crude

#### Example - Expired Electricity Futures in the last year

In [59]:
# Baseload futures represent financial contracts based on the average electricity price over all 
# hours of a delivery period (e.g., day, week, month) rather than peak‑only or off‑peak periods.
ld.discovery.search(
    filter = f"SearchAllCategoryv2 eq 'Commodities' and \
               RCSAssetCategoryLeaf xeq 'Commodity Future' and \
               RCSUnderlyingProductLeaf xeq 'Baseload' and \
               ExchangeName xeq 'European Energy Exchange' and {date_range}",
    order_by = "ExpiryDate desc",
    top = 30,
    select = "DTSubjectName, RIC, ExpiryDate, RCSUnderlyingProductLeaf, DTSimpleType"
)

,DTSubjectName,RIC,ExpiryDate,RCSUnderlyingProductLeaf,DTSimpleType
0,EEX GB Power Base Day Futures Mar 2026,FU11H6,2026-03-11,Baseload,Commodity Future
1,EEX Swiss Base Day Power Future Mar 2026,EEXFC11H6,2026-03-11,Baseload,Commodity Future
2,EEX Hungarian Base Day Power Future Mar 2026,F911H6,2026-03-11,Baseload,Commodity Future
3,EEX Italian Base Day Energy Future Mar 2026,FD11H6,2026-03-11,Baseload,Commodity Future
4,EEX Danish DK1 Power Base Day 11 Energy Future Mar 2026,EEX1D11H6,2026-03-11,Baseload,Commodity Future
5,EEX Spanish Base Day Energy Future Mar 2026,FE11H6,2026-03-11,Baseload,Commodity Future
6,EEX Tokyo Area Power Base Day 11 Energy Future Mar 2026,EEXFT11H6,2026-03-11,Baseload,Commodity Future
7,EEX Greek Power Base Day 11 Energy Future Mar 2026,EEXFF11H6,2026-03-11,Baseload,Commodity Future
8,EEX Phelix-AT Base Day Future Mar 2026,AB11H6,2026-03-11,Baseload,Commodity Future
9,EEX Dutch Power Base Day Future Mar 2026,QB11H6,2026-03-11,Baseload,Commodity Future
10,EEX Czech Base Day Power Future Mar 2026,EEXFX11H6,2026-03-11,Baseload,Commodity Future
11,EEX French Base Day Energy Future Mar 2026,F711H6,2026-03-11,Baseload,Commodity Future
12,EEX Phelix-DE Base Day Energy Future Mar 2026,DB11H6,2026-03-11,Baseload,Commodity Future
13,2D11 MAR6|Swiss Franc/Canadian Dollar 1 Year FX Option,EEX2D11H6,2026-03-11,Baseload,Commodity Future
14,EEX Hungarian Base Day Power Future Mar 2026,F910H6,2026-03-10,Baseload,Commodity Future
15,F710 MAR6|Euro/Swedish Krona Spot Week FX Option,F710H6,2026-03-10,Baseload,Commodity Future
16,FF10 Fut MAR6|US Dollar/Taiwan Dollar Spot Week FX Option,EEXFF10H6,2026-03-10,Baseload,Commodity Future
17,FU10 MAR6|Euro/Hungarian Forint Spot Week FX Option,FU10H6,2026-03-10,Baseload,Commodity Future
18,EEX Phelix-DE Base Day Energy Future Mar 2026,DB10H6,2026-03-10,Baseload,Commodity Future
19,FT10 MAR6|Indonesian Rupiah/Swedish Krona ATM Option,EEXFT10H6,2026-03-10,Baseload,Commodity Future
20,EEX Dutch Power Base Day Future Mar 2026,QB10H6,2026-03-10,Baseload,Commodity Future
21,EEX Spanish Base Day Energy Future Mar 2026,FE10H6,2026-03-10,Baseload,Commodity Future
22,EEX Phelix-AT Base Day Future Mar 2026,AB10H6,2026-03-10,Baseload,Commodity Future
23,2D10 MAR6|Multiple Currencies FX Non-Deliverable Forward,EEX2D10H6,2026-03-10,Baseload,Commodity Future
24,EEX Italian Base Day Energy Future Mar 2026,FD10H6,2026-03-10,Baseload,Commodity Future
25,EEX Danish DK1 Power Base Day 10 Energy Future Mar 2026,EEX1D10H6,2026-03-10,Baseload,Commodity Future
26,EEX Swiss Base Day Power Future Mar 2026,EEXFC10H6,2026-03-10,Baseload,Commodity Future
27,EEX Czech Base Day Power Future Mar 2026,EEXFX10H6,2026-03-10,Baseload,Commodity Future
28,EEX Phelix-DE Base Week Energy Future Mar 2026,DEB2H6,2026-03-09,Baseload,Commodity Future
29,EEX Phelix-DE Base Weekend Future Mar 2026,DWB2H6,2026-03-09,Baseload,Commodity Future

In [50]:
ld.close_session()