## Query
The most basic search that can be performed is the query.  The query is a free-formed text expression, similar to the type of query you can perform within Google, matching against documents within the specified view.

In [1]:
import lseg.data as ld
from lseg.data.content import search
import pandas as pd

# Default session - desktop
ld.open_session()

In [2]:
pd.set_option('display.max_colwidth', 140)
ld.__version__

'2.1.1'

#### Query - Default behavior

In [3]:
# The default syntax for search is to specify a query expression.  By default, search will return a default set of 
# fields (Properties).
ld.discovery.search('IBM')

,BusinessEntity,DocumentTitle,PermID,PI,RIC
0,ORGANISATION,"International Business Machines Corp, Public Company",<NA>,37036,<NA>
1,ORGANISATION,"Banco IBM SA, Private Company",<NA>,76208,<NA>
2,QUOTExEQUITY,"International Business Machines Corp, Ordinary Share, NYSE Consolidated",55839165994,1097326,IBM
3,ORGANISATION,"Ibm International Capital Pte Ltd, Private Company",<NA>,43943628,<NA>
4,ORGANISATION,"Banco Plata SA Institucion de Banca Multiple, Private Company",<NA>,51714311,<NA>
5,ORGANISATION,"Tiers Corporate Bond Backed Certificates Trust Series Ibm 1997 4, Private Company",<NA>,18062670,<NA>
6,QUOTExEQUITY,"Eurex IBM Single Stock Dividend Future Chain Contracts, Equity Future, USD, Eurex",21539944402,156524731,0#I2BM:
7,QUOTExEQUITY,"Eurex IBM Single Stock Equity Future Chain Contracts, Equity Future, USD, Eurex",21481052421,48924732,0#IBMF:
8,QUOTExEQUITY,"Euronext Amsterdam IBM Dividend Future Chain Chain Contracts, Equity Future, USD, Euronext Amsterdam",21612423771,259118763,0#IBMDF:
9,QUOTExEQUITY,"Eurex IBM Single Stock Equity Future Continuation 1, Equity Future, USD, Eurex",21481052892,49450681,IBMFc1

In [4]:
# By default, 10 documents will be returned.  Let's override that.
ld.discovery.search(
    query = 'IBM',
    top = 20
)

,BusinessEntity,DocumentTitle,PermID,PI,RIC
0,ORGANISATION,"International Business Machines Corp, Public Company",<NA>,37036,<NA>
1,ORGANISATION,"Banco IBM SA, Private Company",<NA>,76208,<NA>
2,QUOTExEQUITY,"International Business Machines Corp, Ordinary Share, NYSE Consolidated",55839165994,1097326,IBM
3,ORGANISATION,"Ibm International Capital Pte Ltd, Private Company",<NA>,43943628,<NA>
4,ORGANISATION,"Banco Plata SA Institucion de Banca Multiple, Private Company",<NA>,51714311,<NA>
5,ORGANISATION,"Tiers Corporate Bond Backed Certificates Trust Series Ibm 1997 4, Private Company",<NA>,18062670,<NA>
6,QUOTExEQUITY,"Eurex IBM Single Stock Dividend Future Chain Contracts, Equity Future, USD, Eurex",21539944402,156524731,0#I2BM:
7,QUOTExEQUITY,"Eurex IBM Single Stock Equity Future Chain Contracts, Equity Future, USD, Eurex",21481052421,48924732,0#IBMF:
8,QUOTExEQUITY,"Euronext Amsterdam IBM Dividend Future Chain Chain Contracts, Equity Future, USD, Euronext Amsterdam",21612423771,259118763,0#IBMDF:
9,QUOTExEQUITY,"Eurex IBM Single Stock Equity Future Continuation 1, Equity Future, USD, Eurex",21481052892,49450681,IBMFc1
10,QUOTExEQUITY,"Eurex IBM Single Stock Dividend Future Continuation 1, Equity Future, USD, Eurex",21540050935,156654756,I2BMc1
11,QUOTExEQUITY,"Eurex IBM Single Stock Dividend Future Continuation 2, Equity Future, USD, Eurex",21540050936,156654757,I2BMc2
12,QUOTExEQUITY,"Eurex IBM Single Stock Equity Future Continuation 2, Equity Future, USD, Eurex",21481053949,50092347,IBMFc2
13,QUOTExEQUITY,"Eurex IBM Single Stock Dividend Future Continuation 3, Equity Future, USD, Eurex",21540050937,156654758,I2BMc3
14,QUOTExEQUITY,"Euronext Amsterdam IBM Single Stock Dividend Future Continuation 1, Equity Future, USD, Euronext Amsterdam",21613372305,260213021,IBMDFc1
15,QUOTExEQUITY,"Eurex IBM Single Stock Equity Future Continuation 3, Equity Future, USD, Eurex",21481053950,50092348,IBMFc3
16,QUOTExEQUITY,"Eurex IBM Single Stock Equity Future Continuation 4, Equity Future, USD, Eurex",21481053951,50092349,IBMFc4
17,QUOTExEQUITY,"Eurex IBM Single Stock Dividend Future Continuation 4, Equity Future, USD, Eurex",21540050938,156654759,I2BMc4
18,QUOTExEQUITY,"Eurex IBM Single Stock Dividend Future Continuation 5, Equity Future, USD, Eurex",21540050939,156654760,I2BMc5
19,QUOTExEQUITY,"Eurex IBM Single Stock Equity Future Continuation 5, Equity Future, USD, Eurex",21481053952,50092350,IBMFc5

#### Query Expressions
If we were to type in the following expression, we might come away believing the query will list all personnel within IBM that have a title
of CEO.  While, the results will indicate people related to <b>IBM</b> and people with a title of <b>CEO</b>, we cannot assume they are both.  That is, 
we will see results with the term IBM and CEO listed in the document.

In [5]:
# Match all documents where the term IBM and CEO appear in any order
ld.discovery.search('IBM CEO')

,BusinessEntity,DocumentTitle,PermID,PI
0,PERSON,"Arvind Krishna - International Business Machines Corp - Chairman of the Board, Chief Executive Officer",34417810693,34417810693
1,PERSON,"Alberto Chretin Castillo - Fideicomiso irrevocable numero 6274 - Chairman of the Board, Chief Executive Officer",34415697677,34415697677
2,PERSON,Nicola Hodson - Ibm United Kingdom Ltd - Chief Executive Officer,34426423044,34426423044
3,PERSON,Michael Knagenhjelm - Metamerge As(Ibm Corp) - Chief Executive Officer,34414139687,34414139687
4,PERSON,Lance Crosby - Softlayer Technologies Inc - Chief Executive Officer,34414372380,34414372380
5,PERSON,Bruce Miller - Tarian Software(Ibm) - Chief Executive Officer,34414399995,34414399995
6,PERSON,"Parsa Rohani - Neudesic, LLC - CEO & Founder",34414326563,34414326563
7,PERSON,Frank Chisholm - Aptsoft Corp - CEO & Founder,34414058841,34414058841
8,PERSON,Arvind Krishna - Ibm Ceemea Fz-llc - Chief Executive Officer,34426042635,34426042635
9,PERSON,"Arvind Krishna - IBM Argentina SRL - Chairman of the Board, Chief Executive Officer",34426618219,34426618219

What might give a more favorable result would be to query all documents related to people that contain the term '*IBM*'. From the result, I can visually see
titles and optionally filter out people that are not CEO's.  I can do this by selecting the '**People**' view.
In addition, I'm going to choose specific *child* elements of the **DocumentTitle** field.  As we see in our output from the above requests, the 
'**DocumentTitle**' is selected by default.  This property is a convenient collection of elements that nicely describes the document returned and is
made up of multiple sub-properties such as: '**DTSubjectName**', '**DTSimpleType**', '**DTSource**', and '**DTCharacteristics**'. 

By doing this, I can now see a nice
break-down of the titles (DTCharacteristics), name (DTSubjectName) and company (DTSimpleType).

In [6]:
ld.discovery.search(
    view = search.Views.PEOPLE,
    query = 'IBM',
    select = 'DocumentTitle, DTSubjectName, DTSimpleType, DTSource, DTCharacteristics'
)

,DocumentTitle,DTSubjectName,DTSimpleType,DTCharacteristics
0,"Arvind Krishna - International Business Machines Corp - Chairman of the Board, Chief Executive Officer",Arvind Krishna,International Business Machines Corp,"Chairman of the Board, Chief Executive Officer"
1,Gary D. Cohn - International Business Machines Corp - Vice Chairman,Gary D. Cohn,International Business Machines Corp,Vice Chairman
2,"James J. Kavanaugh - International Business Machines Corp - Chief Financial Officer, Senior Vice President - Finance and Operations",James J. Kavanaugh,International Business Machines Corp,"Chief Financial Officer, Senior Vice President - Finance and Operations"
3,"Nickle LaMoreaux - International Business Machines Corp - Chief Human Resource Officer, Senior Vice President",Nickle LaMoreaux,International Business Machines Corp,"Chief Human Resource Officer, Senior Vice President"
4,Robert Thomas - International Business Machines Corp - Senior Vice President- Software and Chief Commercial Officer,Robert Thomas,International Business Machines Corp,Senior Vice President- Software and Chief Commercial Officer
5,"Nicolas A. Fehring - International Business Machines Corp - Vice President, Controller",Nicolas A. Fehring,International Business Machines Corp,"Vice President, Controller"
6,Alex Gorsky - International Business Machines Corp - Lead Independent Director,Alex Gorsky,International Business Machines Corp,Lead Independent Director
7,Frederick William Mcnabb - International Business Machines Corp - Independent Director,Frederick William Mcnabb,International Business Machines Corp,Independent Director
8,Marianne Catherine Brown - International Business Machines Corp - Independent Director,Marianne Catherine Brown,International Business Machines Corp,Independent Director
9,Joe R. Swedish - International Business Machines Corp - Independent Director,Joe R. Swedish,International Business Machines Corp,Independent Director

In [7]:
# Search for a specific ISIN using query
ld.discovery.search('US046353AQ14')

,BusinessEntity,DocumentTitle,PermID,PI,RIC
0,QUOTExFIXEDINCOMExGOVCORP,"AstraZeneca PLC, Bond Quote, TRACE Eligible, TRADEWEB DIRECT",<NA>,0x00102c8e989a2191,046353AQ1=TWBL
1,QUOTExFIXEDINCOMExGOVCORP,"AstraZeneca PLC, Bond Quote, TRACE Eligible, REAL TIME ALL QUOTES",<NA>,0x00102c4b5ce30dc5,0#046353AQ1=
2,QUOTExFIXEDINCOMExGOVCORP,"NT, Note, US046353AQ14 MiFID II Fine Grained RIC, Deutsche Boerse AG APA Service",196764266323,81620452767,US046353AQ14=DAp
3,INSTRUMENTxFIXEDINCOMExGOVCORP,"AstraZeneca PLC, Plain Vanilla Fixed Coupon Bond, TRACE Eligible AZN 2.375 12-Jun-2022",46645702869,0x00102cb50fde0d55,<NA>

In [8]:
# Narrow the search to only instruments
ld.discovery.search(
    view = search.Views.INSTRUMENTS,
    query = 'US046353AQ14'
)

,BusinessEntity,DocumentTitle,PermID,PI
0,INSTRUMENTxFIXEDINCOMExGOVCORP,"AstraZeneca PLC, Plain Vanilla Fixed Coupon Bond, TRACE Eligible AZN 2.375 12-Jun-2022",46645702869,0x00102cb50fde0d55

#### Query Syntax
A query phrase can support some basic syntax including wildcards, boolean expressions and exact phrase matching.

In [9]:
# Use a specifc term in quotes and the boolean operator to locate specific tankers - use the Content layer 
# to print additional details.
response = search.Definition("'Caribbean Tanker' and Baltic").get_data()
print(f'Matched a total of {response.total} documents')
response.data.df

Matched a total of 40 documents

,BusinessEntity,DocumentTitle,PermID,PI,RIC
0,QUOTExCOMMODITY,"Baltic Exchange TD9 CRB-USG, Commodity Spot, The Baltic Exchange",21815646948,621981,.BACG
1,QUOTExCOMMODITY,"Baltic Exchange Dirty Tanker TD21 Caribbean to US Gulf (50,000mt fuel oil), Commodity Spot, The Baltic Exchange",21717867959,175653765,.BACR
2,QUOTExCOMMODITY,"Baltic Exchange Dirty Tanker TD9 TCE Caribbean to US Gulf Time Charter, Commodity Spot, The Baltic Exchange",21717782063,48950908,.BAAFRTD9
3,QUOTExCOMMODITY,"Baltic Exchange Dirty Tanker TD21 TCE Caribbean to US Gulf (50,000mt fuel oil) Time Charter, Commodity Spot, The Baltic Exchange",21717782060,325658314,.BAAFRTD21
4,QUOTExCOMMODITY,"Baltic Exchange TC 21 US Gulf to Caribbean, Commodity Spot, The Baltic Exchange",21937072473,661825555,.BAGCR
5,QUOTExCOMMODITY,"Baltic Exchange Clean Tanker TC21 TCE US Gulf to Caribbean, Commodity Spot, The Baltic Exchange",21957179764,685232805,.BAGCRTC21
6,QUOTExCOMMODITY,"Argus Tanker Clean Russian Baltic Sea To Caribbean 37Kt Ws Monthly Average PA5002823, Commodity Spot, ARGUS",22096509422,891164902,PA50028230OF0
7,QUOTExCOMMODITY,"Argus Tanker Clean Russian Baltic Sea to Caribbean 37kt Outright PA0041603, Commodity Spot, ARGUS",22030715643,789852453,TNKCRBSCUSO=ARG
8,QUOTExCOMMODITY,"Argus Tanker clean Russian Baltic Sea to Caribbean 37kt WS Monthly Average Outright PA5002823, Commodity Spot, ARGUS",22048240069,815717824,TCRBSTCWMAMO=ARG
9,QUOTExCOMMODITY,"Argus Tanker Clean Russian Baltic Sea To Caribbean 37Kt Monthly Average PA5002822, Commodity Spot, ARGUS",22096509415,891164901,PA50028220OF0

In [10]:
# Use a wildcard (*) to search for references to 'Covid*'.
response=search.Definition(
    query = "Covid*",
    select = "DTSubjectName, DTSimpleType, DTSource, DTCharacteristics"
).get_data()
print(f'Matched a total of {response.total} documents')
response.data.df

Matched a total of 8598 documents

,DTSubjectName,DTSimpleType,DTSource,DTCharacteristics
0,Covidh Technologies Ltd,Public Company,<NA>,<NA>
1,Mass General Brigham Inc,Private Company,<NA>,<NA>
2,Covidh Technologies Ltd,Ordinary Share,BSE Ltd,<NA>
3,Covidien International Finance SA,Private Company,<NA>,<NA>
4,Banconal COVID Relief Facility SARL,Private Company,<NA>,<NA>
5,Covidien Ventures,Private Company,<NA>,<NA>
6,"Europe, Coronavirus (COVID-19), Deaths, Volume",Population,Reuters,Daily
7,"World, Coronavirus (COVID-19), New cases, Volume",Population,Reuters,Daily
8,"China (Mainland), Coronavirus cases cumulative, Beijing, Volume",Population,National Health Commission of the People's Republic of China,Daily
9,"Europe, Coronavirus (COVID-19), New cases, Volume",Population,Reuters,Daily

In [23]:
# List the Vodafone bonds maturing in 2031 with a coupon rate of 5%
# We can achieve this specific query using a special feature called 'tcm' (ticker coupon maturity).
ld.discovery.search(
    query = "vod 5% 2031",
    features = "tcm",
    select = "CouponCurrency, CouponTypeDescription, IssuerLegalName, CouponRate, MaturityDate, ISIN"
)

,CouponCurrency,CouponTypeDescription,IssuerLegalName,CouponRate,MaturityDate,ISIN
0,CHF,Fixed:Plain Vanilla Fixed Coupon,VODAFONE GROUP PUBLIC LIMITED COMPANY,0.5,2031-09-19,CH0337829268

In [24]:
ld.close_session()